name: Build and deploy ASP.Net Core app to Azure Web App - go-azure-ait-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Build
        run: go build -o build/go-app.exe -v

      - name: Test
        run: go test

      - name: Install zip utility
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Archive build artifacts
        run: |
          mkdir -p build/zip
          cp build/go-app.exe build/zip/
          cd build/zip
          zip -r ../go-app.zip ./*
        shell: bash

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D4AF94B3FA3427AAB2FC33B39A9EA50 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A2BA9D7D5EA94F7E93A91317AF9A8B90 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4CDDFE84D61642B1AA7A14141EB4AD22 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: go-azure-ait-test # Replace with your Azure Web App name
          package: build/go-app.zip
