name: Build and deploy Golang app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          if (!(Test-Path -Path "build")) { mkdir build }
          go build -o build/go-app.exe -v
        shell: pwsh

      - name: Test
        run: go test ./...

      - name: Archive build artifacts
        run: |
          mkdir -p build/zip
          cp build/go-app.exe build/zip/
          cd build/zip
          powershell Compress-Archive -Path * -DestinationPath ../go-app.zip
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: build/go-app.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: build

      - name: Deploy to Azure Web App via Kudu
        run: |
          $username = "${{ secrets.AZURE_SCM_USERNAME }}"
          $password = "${{ secrets.AZURE_SCM_PASSWORD }}"
          $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${username}:${password}"))
          $headers = @{ Authorization = "Basic $auth" }
          Invoke-WebRequest -Uri "https://go-azure-ait-test.scm.azurewebsites.net/api/zipdeploy" -Headers $headers -InFile "build/go-app.zip" -Method Post
        shell: pwsh
