name: Build and deploy Golang app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          if (!(Test-Path -Path "build")) { mkdir build }
          go build -o build/go-app.exe -v
        shell: pwsh

      - name: Test
        run: go test ./...

      - name: Archive build artifacts
        run: |
          mkdir -p build/zip
          cp build/go-app.exe build/zip/
          cd build/zip
          powershell Compress-Archive -Path * -DestinationPath ../go-app.zip
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: build/go-app.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: go-azure-ait-test
          package: build/go-app.zip
